# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 08:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('source', models.TextField()),
                ('anonymity', models.CharField(db_index=True, max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('http', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('0', '失效'), ('1', '有效'), ('2', '异常')], db_index=True, max_length=255)),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField()),
                ('success_count', models.IntegerField()),
                ('failure_count', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='proxy',
            unique_together=set([('ip', 'port')]),
        ),
    ]
