# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_auto_20171127_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='invalid_time',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='anonymity',
            field=models.CharField(choices=[('-1', 'unknown'), ('0', '透明'), ('1', '匿名'), ('2', '高匿')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='http',
            field=models.CharField(choices=[('-1', 'unknown'), ('0', 'http'), ('1', 'https'), ('2', 'socks4'), ('3', 'socks5')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='status',
            field=models.CharField(choices=[('0', '失效'), ('1', '有效'), ('2', '异常')], db_index=True, max_length=10),
        ),
    ]
