# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_auto_20171127_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='invalid_time',
        ),
    ]
