# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 09:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BilibiliSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.IntegerField(unique=True)),
                ('season_name', models.CharField(max_length=255)),
                ('bangumi_id', models.IntegerField(db_index=True)),
                ('bangumi_name', models.CharField(max_length=255)),
                ('season_url', models.URLField()),
                ('play_count', models.BigIntegerField()),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
