# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilibiliseason',
            name='status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='bilibiliseason',
            name='season_url',
            field=models.TextField(),
        ),
    ]
