# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20171127_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilibiliseason',
            name='bangumi_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bilibiliseason',
            name='season_name',
            field=models.CharField(max_length=100),
        ),
    ]
