# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 08:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('0', 'BilibiliSeason')], max_length=255)),
                ('source_id', models.IntegerField()),
                ('url', models.TextField()),
                ('status', models.CharField(choices=[('-1', 'url不存在'), ('0', '爬取失败'), ('1', '存储成功'), ('2', '数据异常'), ('3', '字段异常'), ('4', 'other')], db_index=True, max_length=255)),
                ('logs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='spiderlog',
            unique_together=set([('source', 'source_id')]),
        ),
    ]
