# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderlog',
            name='source',
            field=models.CharField(choices=[('0', 'BilibiliSeason')], max_length=10),
        ),
        migrations.AlterField(
            model_name='spiderlog',
            name='status',
            field=models.CharField(choices=[('-1', 'url不存在'), ('0', '爬取失败'), ('1', '存储成功'), ('2', '数据异常'), ('3', '字段异常'), ('4', 'other')], db_index=True, max_length=10),
        ),
    ]
