# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 10:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20171127_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(choices=[('0', '失败'), ('1', '进行中'), ('2', '完成'), ('3', '取消中'), ('4', '已取消')], db_index=True, max_length=10)),
                ('logs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('count', models.IntegerField()),
                ('success', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='spiderlog',
            name='user_log_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='spiderlog',
            unique_together=set([]),
        ),
    ]
