# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20171202_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='log_type',
            field=models.CharField(choices=[('0', 'BilibiliSeason Spider')], db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
    ]
