# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_userlog_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='status',
            field=models.CharField(choices=[('0', '失败'), ('1', '进行中'), ('2', '完成'), ('3', '取消中'), ('4', '已取消'), ('5', '未开始')], db_index=True, max_length=10),
        ),
    ]
