# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 10:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20171228_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='success_detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
